- name: Cockpit
  hosts: localhost
  connection: local
  tags:
    - cockpit
  tasks:
    - name: Enable service
      ansible.builtin.systemd_service:
        name: cockpit
        state: started
        enabled: true
    - name: Configure firewall
      ansible.posix.firewalld:
        service: cockpit
        state: enabled
        permanent: true
        immediate: true
