- name: Core Packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        state: present
        name:
          - NetworkManager-tui
          - yt-dlp
