- name: SSH
  hosts: localhost
  connection: local
  tasks:
    - name: Enable ssh-agent
      ansible.builtin.systemd_service:
        name: ssh-agent.service
        scope: user
        state: started
        enabled: true
      tags:
        - ssh
    - name: Write authorized_keys
      ansible.builtin.copy:
        # TODO: Make configurable
        src: 'authorized_keys'
        dest: '/home/{{ item.key }}/.ssh/authorized_keys'
        owner: '{{ item.key }}'
        group: '{{ item.key }}'
        mode: '0600'
      loop: '{{ users | dict2items }}'
