- name: Install git
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Install git
      ansible.builtin.dnf:
        name:
          - git
        state: latest
    - name: Configure user name
      ansible.builtin.command:
        argv:
          - git
          - config
          - --global
          - user.name
          - "{{ git_user_name }}"
    - name: Configure user email
      ansible.builtin.command:
        argv:
          - git
          - config
          - --global
          - user.email
          - "{{ git_user_email }}"
    - name: Configure default branch
      ansible.builtin.command:
        argv:
          - git
          - config
          - --global
          - init.defaultBranch
          - main
