requires 'IPC::Run',           '20231003.0';
requires 'JSON',               '4.10';
requires 'String::ShellQuote', '1.04';

on 'develop' => sub {
    requires 'Pod::Coverage',       '0.23';
    requires 'Test::CheckManifest', '1.43';
    requires 'Test::Pod',           '1.52';
    requires 'Test::Pod::Coverage', '1.10';
  }
