set dotenv-load := true

default: format test lint

setup:
  carton install

new *args:
  carton run dzil new {{ args }}

# Format everything
format:
  carton run ./scripts/format.sh

# Lint everything
lint:
  carton run ./scripts/lint.sh

# Run tests
test:
  carton run dzil test
