set dotenv-load := true

default: format test lint

setup:
  carton install

new *args:
  dzil new {{ args }}

# Format everything
format:
  ./scripts/format.sh

# Lint everything
lint:
  ./scripts/lint.sh

# Run tests
test:
  dzil test
