set dotenv-load := true

default: format test lint

setup:
  carton install

new *args:
  just dzil new {{ args }}

# Format everything
format:
  carton exec ./scripts/format.sh

# Lint everything
lint:
  carton exec ./scripts/lint.sh

# Run tests
test:
  just dzil test

# Run dzil
dzil *args:
  carton exec -- dzil {{ args }}
