- name: ffmpeg
  hosts: localhost
  connection: local
  tasks:
    - name: Install ffmpeg
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - ffmpeg
          - ffmpeg-libs
          - ffmpeg-devel
