- name: Shell
  hosts: localhost
  connection: local
  vars:
    shell_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  tasks:
    - name: Copy .bashrc
      ansible.builtin.copy:
        src: "bashrc"
        dest: "/home/{{ shell_user }}/.bashrc"
        owner: "{{ shell_user }}"
        group: "{{ shell_user }}"
        mode: "0644"
