- name: Set up packages
  hosts: localhost
  connection: local
  tasks:
    - name: Set up RPM Fusion
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/{{item}}/fedora/rpmfusion-{{item}}-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
      loop:
        - free
        - nonfree
    - name: Update system
      become: true
      dnf:
        name: '*'
        state: latest
        update_cache: true
- name: Set up environment
  hosts: localhost
  connection: local
  vars:
    shell_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    vim_become: true
    vim_owner: "{{ shell_user }}"
    vim_installed_plugins:
      - name: dracula
        repo: "https://github.com/dracula/vim.git"
        type: start
  roles:
    - role: jfhbrook.vim
  tasks:
    - name: Copy .bashrc
      ansible.builtin.copy:
        src: "bashrc"
        dest: ".bashrc"
        owner: "{{ shell_user }}"
        group: "{{ shell_user }}"
        mode: "0644"
    - name: Copy .vimrc
      ansible.builtin.copy:
        src: "vimrc"
        dest: ".vimrc"
        owner: "{{ shell_user }}"
        group: "{{ shell_user }}"
        mode: "0644"
      tags:
        - skip_ansible_lint
    - name: Install CLI tools
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - bat
          - btop
          - gh
          - git
          - htop
          - jq
          - neofetch
          - ranger
          - ripgrep
          - the_silver_searcher
          - tmux
          - yq
