- name: Set up packages
  hosts: localhost
  connection: local
  tasks:
    - name: Set up RPM Fusion
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/{{item}}/fedora/rpmfusion-{{item}}-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
      loop:
        - free
        - nonfree
    - name: Enable fedora-cisco-openh264
      community.general.dnf_config_manager:
        name: fedora-cisco-openh264
        state: enabled
    - name: Update system
      become: true
      dnf:
        name: '*'
        state: latest
        update_cache: true
- name: Set up environment
  hosts: localhost
  connection: local
  vars:
    shell_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    vim_become: true
    vim_owner: "{{ shell_user }}"
    vim_installed_plugins:
      - name: dracula
        repo: "https://github.com/dracula/vim.git"
        type: start
      - name: vim-which-key
        repo: "https://github.com/liuchengxu/vim-which-key.git"
        type: start
      - name: fzf
        repo: "https://github.com/junegunn/fzf"
        type: start
      - name: fzf.vim
        repo: "https://github.com/junegunn/fzf.vim"
        type: start
  roles:
    - role: jfhbrook.vim
  tasks:
    - name: Copy .bashrc
      ansible.builtin.copy:
        src: "bashrc"
        dest: "/home/{{ shell_user }}/.bashrc"
        owner: "{{ shell_user }}"
        group: "{{ shell_user }}"
        mode: "0644"
    - name: Copy .vimrc
      ansible.builtin.copy:
        src: "vimrc"
        dest: "/home/{{ shell_user }}/.vimrc"
        owner: "{{ shell_user }}"
        group: "{{ shell_user }}"
        mode: "0644"
      tags:
        - skip_ansible_lint
    - name: Install CLI tools
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - bat
          - btop
          - fzf
          - gh
          - git
          - htop
          - jq
          - neofetch
          - ranger
          - ripgrep
          - the_silver_searcher
          - tmux
          - yq
    - name: Install PulseAudio
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - pulseaudio 
          - pulseaudio-libs 
          - pulseaudio-libs-devel 
          - pulseaudio-module-bluetooth 
          - pulseaudio-utils 
          - pamix 
          - pamixer
    - name: Install NetworkManager-tui
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - NetworkManager-tui
    - name: Install ffmpeg
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - ffmpeg
          - ffmpeg-libs
          - ffmpeg-devel
    - name: Enable ssh-agent
      ansible.builtin.systemd_service:
        name: ssh-agent.service
        scope: user
        state: started
        enabled: true
    - name: Install mDNS packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - nss-mdns
          - avahi
    - name: Enable Avahi daemon
      become: true
      ansible.builtin.systemd_service:
        name: avahi-daemon.service
        state: started
        enabled: true
    - name: Allow mDNS traffic
      become: true
      ansible.posix.firewalld:
        service: mdns
        state: enabled
        permanent: true
    - name: Set git user name
      community.general.git_config:
        name: user.name
        value: "Josh Holbrook"
        scope: global
    - name: Set git user email
      community.general.git_config:
        name: user.email
        value: "josh.holbrook@gmail.com"
        scope: global
    - name: Set git default branch
      community.general.git_config:
        name: init.defaultBranch
        value: main
        scope: global
