- name: nginx-formatter
  hosts: localhost
  connection: local
  tags:
    - development
  tasks:
    - name: Install nginx-formatter
      become: true
      become_user: '{{ item.key }}'
      ansible.builtin.unarchive:
        src: 'https://github.com/soulteary/nginx-formatter/releases/download/v{{ nginx_formatter_version }}/nginx-formatter_{{ nginx_formatter_version }}_linux_amd64.tar.gz'
        dest: '/home/{{ item.key }}/.local/bin'
        remote_src: true
        include:
          - nginx-formatter
        mode: '0755'
        owner: '{{ item.key }}'
        group: '{{ item.key }}'
      when: development
      loop: '{{ users | dict2items }}'
      vars:
        nginx_formatter_version: '1.1.1'
