- name: SSH
  hosts: localhost
  connection: local
  tasks:
    - name: Enable ssh-agent
      become: true
      become_user: '{{ item.key }}'
      ansible.builtin.systemd_service:
        name: ssh-agent.service
        scope: user
        state: started
        enabled: true
      loop: '{{ users | dict2items }}'
    - name: 'Add authorized keys for user'
      include_tasks: ./keys.yml
      loop: '{{ users | dict2items }}'
      loop_control:
        loop_var: user
    - name: Add SSH agent to ~/.bashrc
      ansible.builtin.blockinfile:
        path: '/home/{{ item.key }}/.bashrc'
        marker: '# {mark} SSH agent'
        marker_begin: Begin
        marker_end: End
        prepend_newline: true
        append_newline: true
        block: 'eval "$(ssh-agent -s)" > /dev/null'
      loop: '{{ users | dict2items }}'
