- name: Add SSH agent to ~/.bashrc
  ansible.builtin.blockinfile:
    path: '/home/{{ item.key }}/.bashrc'
    marker: '# {mark} SSH agent'
    marker_begin: Begin
    marker_end: End
    prepend_newline: true
    append_newline: true
    block: 'eval "$(ssh-agent -s)" > /dev/null'
