- name: Bluetooth
  hosts: localhost
  connection: local
  tasks:
    - name: Write source.conf
      ansible.builtin.copy:
        src: 'source.conf'
        dest: '/etc/bluetooth/source.conf'
        owner: root
        group: root
        mode: '0644'
      notify: Restart bluetooth
  handlers:
    - name: Restart bluetooth
      ansible.builtin.systemd_service:
        name: bluetooth
        state: restarted
