# See: https://rpmfusion.org/Howto/Multimedia
- name: Check if full FFMpeg is enabled
  ansible.builtin.shell: |
    if ! rpm -qa | grep -E '^ffmpeg-free-' > /dev/null; then
      echo 'true'
    fi
  register: ffmpeg_enabled_check
  changed_when: false
  tags:
    - audio
- name: Switch DNF to Full FFMpeg
  ansible.builtin.shell: |
    dnf swap ffmpeg-free ffmpeg --allowerasing
    dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
  when: not ffmpeg_enabled_check.stdout|bool
- name: Install Audio Packages
  ansible.builtin.dnf:
    state: present
    name:
      # bluetooth
      - bluez
      - bluez-tools
      # ffmpeg
      - intel-media-driver
      - ffmpeg-libs
      - ffmpeg-devel
      # pipewire
      - helvum
      # project M
      - projectM-pulseaudio
      # pulseaudio
      - pipewire-pulseaudio
      - pulseaudio-utils
      - pamix
      - pamixer
