- name: Pipewire
  hosts: localhost
  connection: local
  tags:
    - audio
  tasks:
    - name: Create /etc/pipewire
      ansible.builtin.file:
        path: /etc/pipewire
        state: directory
        owner: root
        group: root
        mode: '0755'
