- name: PulseAudio
  hosts: localhost
  connection: local
  tasks:
    - name: Enable pipewire-pulse service
      become: true
      become_user: '{{ item.key }}'
      ansible.builtin.systemd_service:
        name: pipewire-pulse
        state: started
        scope: user
        enabled: true
      loop: '{{ users | dict2items }}'
    - name: Write pipewire-pulse.conf
      ansible.builtin.copy:
        src: 'pipewire-pulse.conf'
        dest: '/etc/pipewire/pipewire-pulse.conf'
        owner: root
        group: root
        mode: '0644'
