- name: Desktop Packages
  hosts: all
  connection: local
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name:
          # 1password
          - 1password
          - 1password-cli
          # kitty
          - kitty
        state: present
