apiVersion: coprctl/v1alpha1
kind: package-scm
metadata:
  name: "bt-audio"
spec:
  auto_rebuild: false
  projectname: "stardeck"
  clone-url: "https://github.com/jfhbrook/stardeck"
  commit: null
  subdir: "packages/bt-audio"
  spec: "bt-audio.spec"
  type: git
  method: make_srpm
  enable_net: false
