- name: Plusdeck
  hosts: localhost
  connection: local
  tags:
    - plusdeck
  tasks:
    - name: Create plusdeck group
      ansible.builtin.group:
        name: plusdeck
        state: present
    - name: Add user to plusdeck group
      ansible.builtin.user:
        name: '{{ item.key }}'
        groups: plusdeck
        append: yes
      loop: '{{ users | dict2items }}'
    - name: Enable service
      ansible.builtin.systemd_service:
        name: plusdeck
        state: started
        enabled: true
