- name: Neovim
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Install plug
      ansible.builtin.shell:
        cmd: >
          sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        creates: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
