- name: Terraform
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Install dnf-plugins-core
      become: true
      ansible.builtin.dnf:
        name: dnf5-plugins
        state: present
    - name: Set up Hashicorp RPM Repository
      become: true
      ansible.builtin.command:
        argv:
          - dnf
          - config-manager
          - addrepo
          - "--from-repofile=https://rpm.releases.hashicorp.com/fedora/hashicorp.repo"
        creates: /etc/yum.repos.d/hashicorp.repo
    - name: Install packages
      ansible.builtin.dnf:
        name: terraform
        state: present
