- name: CLI Tools
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - bat
          - btop
          - eza
          - fd-find
          - fzf
          - gh
          - htop
          - just
          - jq
          - neofetch
          - pandoc
          - ranger
          - ripgrep
          - the_silver_searcher
          - tmux
          - yq
    - name: Download gomplate
      ansible.builtin.get_url:
        url: "https://github.com/hairyhenderson/gomplate/releases/download/v4.3.0/gomplate_linux-amd64"
        dest: "{{ ansible_env.HOME }}/.local/bin/gomplate"
        mode: "755"
