- name: Core
  import_playbook: ./core/packages.yml
- name: Cockpit
  import_playbook: ./cockpit/packages.yml
- name: Vim
  import_playbook: ./vim/packages.yml
- name: Audio
  import_playbook: ./audio/packages.yml
- name: Desktop
  import_playbook: ./desktop/packages.yml
- name: Mopidy
  import_playbook: ./mopidy/packages.yml
- name: Other
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        state: present
        name:
          - python-crystalfontz
          - plusdeck
