- name: Packages
  hosts: localhost
  connection: local
  tasks:
    - name: Core
      include_tasks: ./core/packages.yml
    - name: Cockpit
      include_tasks: ./cockpit/packages.yml
    - name: Vim
      include_tasks: ./vim/packages.yml
    - name: Audio
      include_tasks: ./audio/packages.yml
    - name: Desktop
      include_tasks: ./desktop/packages.yml
    - name: Mopidy
      include_tasks: ./mopidy/packages.yml
    - name: File Sharing
      include_tasks: ./filesharing/packages.yml
    - name: Install other packages
      ansible.builtin.dnf:
        state: present
        name:
          - kdotool
          - crystalfontz
          - plusdeck
    - name: Development
      include_tasks: ./development/packages.yml
      when: development
