- name: Plusdeck
  hosts: localhost
  connection: local
  tasks:
    - name: Create plusdeck group
      ansible.builtin.group:
        name: plusdeck
        state: present
    - name: Add user to plusdeck group
      ansible.builtin.user:
        name: '{{ item.key }}'
        groups: plusdeck
        append: yes
      loop: '{{ users | dict2items }}'
