- name: Web
  hosts: localhost
  connection: local
  tags:
    - web
  tasks:
    - name: 'Configure firewall'
      ansible.posix.firewalld:
        service: '{{ item }}'
        state: enabled
        permanent: true
        immediate: true
      loop:
        - http
        - https
