- name: Vim
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        state: present
        name:
          - fzf
          - bat
          - ripgrep
          - the_silver_searcher
          - perl
          - ctags
