- name: Dialout
  hosts: localhost
  connection: local
  tags:
    - dialout
  tasks:
    - name: Add user to dialout group
      ansible.builtin.user:
        name: '{{ item.key }}'
        groups: dialout
        append: yes
      loop: '{{ users | dict2items }}'
