- name: Packages
  hosts: localhost
  connection: local
  tasks:
    - name: Core
      include_tasks: ./core/packages.yml
    - name: Audio
      include_tasks: ./audio/packages.yml
    - name: Cockpit
      include_tasks: ./cockpit/packages.yml
    - name: Crystalfontz
      include_tasks: ./crystalfontz/packages.yml
    - name: Desktop
      include_tasks: ./desktop/packages.yml
    - name: File Sharing
      include_tasks: ./filesharing/packages.yml
    - name: Media
      include_tasks: ./media/packages.yml
    - name: Mopidy
      include_tasks: ./mopidy/packages.yml
    - name: Network
      include_tasks: ./network/packages.yml
    - name: Plusdeck
      include_tasks: ./plusdeck/packages.yml
    - name: Stardeck
      include_tasks: ./stardeck/packages.yml
    - name: Vim
      include_tasks: ./vim/packages.yml
    - name: Web
      include_tasks: ./web/packages.yml
    - name: Development
      include_tasks: ./development/packages.yml
      when: development
