- name: Repositories
  hosts: localhost
  connection: local
  tasks:
    - name: Core
      import_tasks: ./core/repositories.yml
    - name: Desktop
      import_tasks: ./desktop/repositories.yml
    - name: Development
      import_tasks: ./development/repositories.yml
      when: development
