- name: Shell Hooks
  hosts: localhost
  connection: local
  tags:
    - shell
  tasks:
    - name: SSH
      include_tasks: ./ssh/shell.yml
      loop: '{{ users | dict2items }}'
    - name: Starship
      include_tasks: ./starship/shell.yml
      loop: '{{ users | dict2items }}'
    - name: Go
      include_tasks: ./development/go-dev/shell.yml
      loop: '{{ users | dict2items }}'
    - name: Rust
      include_tasks: ./development/rust-dev/shell.yml
      loop: '{{ users | dict2items }}'
    - name: Node.js
      include_tasks: ./development/node-dev/shell.yml
      loop: '{{ users | dict2items }}'
    - name: Perl
      include_tasks: ./development/perl-dev/shell.yml
      loop: '{{ users | dict2items }}'
