- name: System Update
  hosts: all
  connection: local
  tags:
    - update
  tasks:
    - name: Update packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
