set dotenv-load := true

# Lint everything
lint:
  perlcritic --harsh ./Stardeck/lib/*.pm ./bin/*  # TODO: Pass --cruel

# Format everything
format:
  perltidy -b -bext='/' ./Stardeck/lib/*.pm ./bin/*
