- name: Pipewire
  import_playbook: pipewire.yml
- name: Pulseaudio
  import_playbook: pulseaudio.yml
- name: Bluetooth
  import_playbook: bluetooth.yml
- name: FFMpeg
  import_playbook: ffmpeg.yml
- name: Plus Deck 2C
  import_playbook: plusdeck.yml
