- name: PulseAudio
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - pipewire-pulseaudio
          - pulseaudio-utils 
          - pamix 
          - pamixer
    - name: Enable pipewire-pulse service
      ansible.builtin.systemd_service:
        name: pipewire-pulse
        state: started
        scope: user
        enabled: true
    - name: Write pipewire-pulse.conf
      become: true
      ansible.builtin.copy:
        src: "pipewire-pulse.conf"
        dest: "/etc/pipewire/pipewire-pulse.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Restart pipewire-pulse
  handlers:
    - name: Restart pipewire-pulse
      become: true
      ansible.builtin.systemd_service:
        name: pipewire-pulse
        state: restarted
