# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

# ssh-agent
# see: https://unix.stackexchange.com/questions/132791/have-ssh-add-be-quiet-if-key-already-there
ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_ed25519  | awk '{print $2}')" || ssh-add ~/.ssh/id_ed25519
