install:
  kpackagetool6 --type=KWin/Script -i .
  @just enable

enable:
  kwriteconfig6 --file kwinrc --group Plugins --key myscriptEnabled true
  @just reconfigure

reconfigure:
  dbus-send --session --dest=org.kde.KWin --print-reply /KWin reconfigure
