- name: RPM Fusion
  hosts: localhost
  connection: local
  tasks:
    - name: Set up RPM Fusion
      become: true
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/{{item}}/fedora/rpmfusion-{{item}}-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
      loop:
        - free
        - nonfree
    - name: Enable fedora-cisco-openh264
      become: true
      community.general.dnf_config_manager:
        name: fedora-cisco-openh264
        state: enabled
