- name: Vim
  hosts: localhost
  connection: local
  vars:
    shell_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    vim_become: true
    vim_owner: "{{ shell_user }}"
    vim_installed_plugins:
      - name: dracula
        repo: "https://github.com/dracula/vim.git"
        type: start
      - name: vim-which-key
        repo: "https://github.com/liuchengxu/vim-which-key.git"
        type: start
      - name: fzf
        repo: "https://github.com/junegunn/fzf"
        type: start
      - name: fzf.vim
        repo: "https://github.com/junegunn/fzf.vim"
        type: start
  roles:
    - role: jfhbrook.vim
  tasks:
    - name: Install Vim dependencies
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - fzf
          - bat
          - ripgrep
          - the_silver_searcher
          - perl
          - ctags
    - name: Copy .vimrc
      ansible.builtin.copy:
        src: "vimrc"
        dest: "/home/{{ shell_user }}/.vimrc"
        owner: "{{ shell_user }}"
        group: "{{ shell_user }}"
        mode: "0644"
      tags:
        - skip_ansible_lint
