- name: SSL Self-Signed Certificate
  ansible.builtin.import_playbook: ./certificate.yml
- name: Web
  hosts: localhost
  connection: local
  tags:
    - web
  tasks:
    - name: Write NGINX config
      ansible.builtin.template:
        src: 'nginx.conf'
        dest: '/etc/nginx/nginx.conf'
        owner: root
        group: root
        mode: '0644'
      notify: Reload NGINX
    - name: Allow NGINX to proxy connections
      ansible.builtin.command:
        argv:
          - setsebool
          - -P
          - httpd_can_network_connect
          - '1'
    - name: 'Configure firewall'
      ansible.posix.firewalld:
        service: '{{ item }}'
        state: enabled
        permanent: true
        immediate: true
      loop:
        - http
        - https
  handlers:
    - name: Reload NGINX
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
