- name: Set up RPM Fusion
  tags:
    - core
  # TODO: Using the dnf module here yields an error...
  ansible.builtin.command:
    argv:
      - dnf
      - install
      - '-y'
      - 'https://mirrors.rpmfusion.org/{{item}}/fedora/rpmfusion-{{item}}-release-{{ansible_distribution_major_version}}.noarch.rpm'
  loop:
    - free
    - nonfree
  register: rpmfusion_install
  changed_when: '"Nothing to do." not in rpmfusion_install.stdout'
- name: Enable fedora-cisco-openh264
  tags:
    - core
  ansible.builtin.command:
    argv:
      - dnf
      - config-manager
      - setopt
      - fedora-cisco-openh264.enabled=1
- name: Enable Joshiverse COPR
  tags:
    - core
  community.general.copr:
    name: jfhbrook/joshiverse
    state: enabled
