- name: Install 1Password
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Import 1password GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "https://downloads.1password.com/linux/keys/1password.asc"
    - name: Add 1password repository
      ansible.builtin.yum_repository:
        name: "1password"
        state: present
        description: "1Password Stable Channel"
        file: "1password"
        baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
        gpgcheck: true
    - name: Install 1password and 1password-cli
      ansible.builtin.dnf:
        name:
          - 1password
          - 1password-cli
        state: latest
