- name: File Sharing
  hosts: all
  connection: local
  tags:
    - filesharing
  tasks:
    - name: 'Add {{ item.name }} to usershares group'
      ansible.builtin.user:
        name: '{{ item.name }}'
        groups: usershares
        append: true
      loop: '{{ samba_users }}'
    - name: Configure Samba
      ansible.builtin.include_role:
        name: vladgh.samba.server
    - name: Set SELinux Context on Shares Root
      ansible.builtin.shell: >
        semanage fcontext --add --type "samba_share_t" "{{ samba_shares_root }}(/.*)?"; restorecon -R "{{ samba_shares_root }}"
    - name: Configure firewall
      ansible.posix.firewalld:
        service: samba
        state: enabled
        permanent: true
        immediate: true
