- name: File Sharing Packages
  hosts: all
  connection: local
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - samba
          - kdenetwork-filesharing
        state: present
