- name: Mopidy
  hosts: localhost
  connection: local
  tags:
    - mopidy
  tasks:
    - name: Enable service
      ansible.builtin.systemd_service:
        name: mopidy
        state: started
        enabled: true
    - name: Configure firewall
      ansible.posix.firewalld:
        port: 6680/tcp
        state: enabled
        permanent: true
        immediate: true
    - name: Write mopidy.conf
      become: true
      ansible.builtin.template:
        src: 'mopidy.conf'
        dest: '/etc/mopidy/mopidy.conf'
        owner: root
        group: root
        mode: '0644'
      notify: Restart mopidy
  handlers:
    - name: Restart mopidy
      become: true
      ansible.builtin.systemd_service:
        name: mopidy
        state: restarted
