set dotenv-load := true

setup:
  ./scripts/setup.sh

# Format everything
format: setup
  carton run ./scripts/format.sh

# Lint everything
lint: setup
  carton run ./scripts/lint.sh

# Run tests
test: setup
  carton run ./scripts/test.sh
