set dotenv-load := true

setup:
  ./scripts/setup.sh

new *args:
  carton run dzil new {{ args }}

# Format everything
format:
  carton run ./scripts/format.sh

# Lint everything
lint:
  carton run ./scripts/lint.sh

# Run tests
test:
  carton run ./scripts/test.sh
