set dotenv-load := true

# Format everything
format:
  carton run ./scripts/format.sh

# Lint everything
lint:
  carton run ./scripts/lint.sh

# Run tests
test:
  cd Stardeck && perl Makefile.PL && make test
