default:
  @just serve

# Install PaperMod
install:
  git submodule update --init --recursive 

# Update PaperMod
update:
  git submodule update --remote --merge

# Create new content
new *argv:
  hugo new content {{ argv }}

# Serve the development site
serve:
  hugo serve --buildDrafts

# Build the site
build:
  hugo build

# rsync build to /srv/portal
rsync: build
  sudo ./scripts/rsync.sh
