- name: Git CLI
  hosts: localhost
  connection: local
  tasks:
    - name: Install git
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - git
    - name: Set git user name
      community.general.git_config:
        name: user.name
        value: "Josh Holbrook"
        scope: global
    - name: Set git user email
      community.general.git_config:
        name: user.email
        value: "josh.holbrook@gmail.com"
        scope: global
    - name: Set git default branch
      community.general.git_config:
        name: init.defaultBranch
        value: main
        scope: global
