- name: Bluetooth
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - bluez
          - bluez-tools
