- name: Dialout
  hosts: localhost
  connection: local
  tasks:
    - name: Add user to dialout group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user | default(lookup('env', 'USER')) }}"
        groups: dialout
        append: yes
