- name: Install GitHub CLI
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Install config-manager
      ansible.builtin.dnf:
        name: 'dnf-command(config-manager)'
        state: latest
    - name: Set up GitHub CLI RPM Repository
      become: true
      ansible.builtin.command:
        - dnf
        - config-manager
        - --add-repo
        - https://cli.github.com/packages/rpm/gh-cli.repo
    - name: Install gh CLI
      ansible.builtin.dnf:
        name: gh
        state: latest
