- name: mDNS
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - nss-mdns
          - avahi
    - name: Enable Avahi daemon
      become: true
      ansible.builtin.systemd_service:
        name: avahi-daemon.service
        state: started
        enabled: true
    - name: Allow mDNS traffic
      become: true
      ansible.posix.firewalld:
        service: mdns
        state: enabled
        permanent: true
