- name: Mopidy
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - mopidy
          - python-mopidy-iris
          - python-mopidy-local
          - python-mopidy-ytmusic
    - name: Enable service
      become: true
      ansible.builtin.systemd_service:
        name: mopidy
        state: started
        enabled: true
    - name: Configure firewall
      become: true
      ansible.builtin.shell: >
        firewall-cmd --add-port=6680/tcp;
        firewall-cmd --add-port=6680/tcp --permanent
    - name: Write mopidy.conf
      become: true
      ansible.builtin.copy:
        src: "mopidy.conf"
        dest: "/etc/mopidy/mopidy.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Restart mopidy
      tags:
        - skip_ansible_lint
  handlers:
    - name: Restart mopidy
      become: true
      ansible.builtin.systemd_service:
        name: mopidy
        state: restarted
        enabled: true
