- name: Mopidy
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - mopidy
          - python-mopidy-iris
          - python-mopidy-local
          - python-mopidy-ytmusic
