- name: Install Rust Development Environment
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Install rustup
      ansible.builtin.shell:
        cmd: >
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        creates: "{{ ansible_env.HOME }}/.cargo"
    - name: Update Rust
      ansible.builtin.command:
        argv:
          - "{{ ansible_env.HOME }}/.cargo/bin/rustup"
          - update
          - "{{ item }}"
        loop:
          - stable
          - nightly
    - name: Install rust-analyzer
      ansible.builtin.dnf:
        name: rust-analyzer
        state: latest
