- name: Install yt-dlp
  hosts: localhost
  connection: local
  tasks:
    - name: Install yt-dlp
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - yt-dlp
